# Generated by Django 3.2.20 on 2023-08-14 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20230814_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='recipe_bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
