# Generated by Django 3.2.20 on 2023-08-19 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=140, unique=True, validators=[django.core.validators.RegexValidator('^[a-z\\d\\-_\\s]+$', 'Only alphanumeric and space characters are allowed.')]),
        ),
    ]
