# Generated by Django 3.2.20 on 2023-08-19 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230819_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=140, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_title', message='Title must be Alphanumeric', regex='/^[\\w\\-\\s]+$/')]),
        ),
    ]
