# Generated by Django 3.2.20 on 2023-08-19 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(help_text='Format: Letters, Numbers, Hyphens & Underscores only', max_length=140, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_title', message='Title must be Alphanumeric', regex='^[\\w\\-\\s]+$')]),
        ),
    ]
