# Generated by Django 3.2.20 on 2023-08-19 16:23

import django.core.validators
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0018_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_alt',
            field=models.CharField(help_text='Max Length 140 Characters', max_length=140),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Status: Draft or Published'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='summary',
            field=models.TextField(help_text='Summarise your recipe in 240 Characters', max_length=240),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-seperated list of tags. Eg. Pasta, Italian', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(help_text='Format: Letters, Numbers, Hyphens & Underscores only.', max_length=140, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_title', message='Title must be Alphanumeric', regex='^[\\w\\-\\s]+$')]),
        ),
    ]
