# Generated by Django 3.2.20 on 2023-08-22 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20230819_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_alt',
            field=models.CharField(default='Recipe Repo Logo', help_text='If no picture added, leave default text', max_length=70),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='summary',
            field=models.TextField(help_text='Summarise your recipe in 240 Characters', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(help_text='Format: Letters, Numbers, Hyphens & Underscores only.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_title', message='Title: Letters, Numbers, Hyphens & Underscores only.', regex='^[\\w\\-\\s]+$')]),
        ),
    ]
