# Generated by Django 3.2.20 on 2023-08-23 12:04

import cloudinary.models
from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20230822_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_alt',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default', help_text='Images are auto-cropped to 1:1 ratio', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=django_quill.fields.QuillField(default='Write your ingredients here'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=django_quill.fields.QuillField(default='Write your instructions here'),
        ),
    ]
