# Generated by Django 3.2.20 on 2023-08-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20230823_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(default='Directions'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='zutaten',
            field=models.TextField(default='Zutaten'),
        ),
    ]
