# Generated by Django 3.2.20 on 2023-08-25 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20230825_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='zutaten',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(help_text='Format: Letters, Numbers, Hyphens & Underscores only', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_title', message='Title: Letters, Numbers, Hyphens & Underscores only.', regex='^[\\w\\-\\s]+$')]),
        ),
    ]
